export const ROUTES = {
  ADMIN: '/admin',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_PRODUCTS_CREATE: '/admin/products/create',
  ADMIN_CATEGORIES: '/admin/categories',
  ADMIN_CATEGORIES_CREATE: '/admin/categories/create',
  ADMIN_FILES: '/admin/files',
  ADMIN_USERS: '/admin/users',
  BASE: '/',
  SIGN_IN: '/sign-in',
  SIGN_UP: '/sign-up',
  VERIFY_EMAIL: '/verify-email',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
} as const;
